name: Build and Push
on:
  push:
    branches: [ trunk ]
jobs:
  build_and_test:
    runs-on: windows-latest
    env:
      NUGET_SOURCE: ${{ secrets.NUGET_SOURCE }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Install Nuke
        run: dotnet tool install Nuke.GlobalTool --global
      - name: Nuget push
        run: nuke -Target Push
